apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: infrastructure_provisioning
  title: provision infrastructure through conditional inputs
  description: A demo to run the pipeline based on conditional skips powered by
    IDP templates
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - nextjs
    - react
    - javascript
spec:
  owner: shashank.dwivedi@harness.io
  type: service
parameters:
  - title: infrastructure_provisioning
    type: object
    required:
      - environment_type
      - owner
    properties:
      owner:
        title: Choose an Owner for the Service
        type: string
        ui:field: OwnerPicker
        ui:options:
          allowedKinds:
            - Group
      token:
        title: Harness Token
        type: string
        ui:widget: password
        ui:field: HarnessAuthToken
      environment_type:
        title: environment_type
        type: string
        description: Name of the environment where you want to provision a resource
        enum:
          - dev
          - staging
          - prod
      infracomponent:
        title: infra component
        type: object
        properties:
          resource_type:
            title: resource_type
            type: string
            description: Name of the resource that you want to provision
            enum:
              - s3
              - vpc
              - sns
              - glue
              - sqs
        required:
          - resource_type
        dependencies:
          resource_type:
            oneOf:
              - properties:
                  resource_type:
                    enum:
                      - s3
                      - vpc
                  Operationtype:
                    $ref: "#/myregion/operation"
    myregion:
      operation:
        title: region
        type: object
        properties:
          ChooseRegion:
            type: string
            enum:
              - Region A
              - Region B
              - Region C
    steps:
      - id: trigger
        name: Only Non Production Environments
        if: ${{ parameters.environment_type === "staging" and parameters.environment_type === "dev" }}
        action: trigger:harness-custom-pipeline
        input:
          message: Non Production Environments
          url: https://qa.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/module/idp-admin/orgs/shashank/projects/shashank_idp_test/pipelines/provision_infrastructure/pipeline-studio?storeType=INLINE
          inputset:
            resource_type: ${{ parameters.resource_type }}
            environment_type: ${{ parameters.environment_type }}
          apikey: ${{ parameters.token }}
      - id: trigger
        name: Only Production Environments
        if: ${{ parameters.environment_type === "prod" }}
        action: trigger:harness-custom-pipeline
        input:
          message: Production Environments
          url: https://qa.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/module/idp-admin/orgs/shashank/projects/shashank_idp_test/pipelines/Production_Infrastructure_Provisioning/pipeline-studio?storeType=INLINE
          inputset:
            resource_type: ${{ parameters.resource_type }}
            environment_type: ${{ parameters.environment_type }}
          apikey: ${{ parameters.token }}
    output:
      links:
        - title: Pipeline Details
          url: ${{ steps.trigger.output.PipelineUrl }}

  
